PostgreSQL:
  PROTOCOL: 'postgresql'
  USERNAME: 'postgres'
  PASSWORD: 'postgres'
  HOSTNAME: 'localhost'
  PORT: 5432
  DATABASE: 'Inkosi'
  SCHEMA: 'development'
  PARAMETERS: ''
  
MongoDB:
  PROTOCOL: mongodb
  USERNAME: test
  PASSWORD: test
  HOSTNAME: localhost
  PORT: 27017
  DATABASE: production
  PARAMETERS: ''
  TLS: false

  COLLECTIONS:
    Log: 'Logs'

API:
  AllowedIPAddresses: '*'
  TokenAuthentication: false

DockerInstance: false