PostgreSQL:
  PROTOCOL: 'postgresql'
  USERNAME: 'postgres'
  PASSWORD: 'postgres'
  HOSTNAME: 'localhost'
  PORT: 5432
  DATABASE: 'Inkosi'
  SCHEMA: 'development'
  PARAMETERS: ''
  
MongoDB:
  PROTOCOL: mongodb
  USERNAME: test
  PASSWORD: test
  HOSTNAME: localhost
  PORT: 27017
  DATABASE: production
  PARAMETERS: ''
  TLS: false

  COLLECTIONS:
    Log: 'Logs'
    Trade: 'Trades'

API:
  AllowedIPAddresses: '*'
  TokenAuthentication: true
  IPAddressCorrespondence: false
  TimeActivity: 
    days: 0
    hours: 6
    minutes: 30
    seconds: 30

Policies:
  Administrator:
    - portfolio_manager_full_access
    - administrator_full_access
  Investor:
    - basic_investor_access

DockerInstance: false