PostgreSQL:
  PROTOCOL: "postgresql"
  USERNAME: "postgres"
  PASSWORD: "postgres"
  HOSTNAME: "localhost"
  PORT: 5432
  DATABASE: "Inkosi"
  SCHEMA: "development"
  PARAMETERS: ""

MongoDB:
  PROTOCOL: mongodb
  USERNAME: test
  PASSWORD: test
  HOSTNAME: localhost
  PORT: 27017
  DATABASE: production
  PARAMETERS: ""
  TLS: false

  COLLECTIONS:
    Log: "Logs"
    Trade: "Trades"

API:
  AllowedIPAddresses: "*"
  TokenAuthentication: true
  IPAddressCorrespondence: false
  TimeActivity:
    days: 0
    hours: 6
    minutes: 30
    seconds: 30
  APIs:
    - MetaTrader5

Policies:
  Administrator:
    - ADMINISTRATOR_IFM_FULL_ACCESS
    - ADMINISTRATOR_FM_FULL_ACCESS
    - ADMINISTRATOR_PM_FULL_ACCESS
  Investor:
    - INVESTOR_DASHBOARD_VISUALISATION
    - INVESTOR_SAMPLING_SCENARIOS
    - INVESTOR_BACKTEST_ALL

RiskManagement:
  Models:

TechnicalIndicators:
  MovingAveragePeriod: 20

DefaultAdministrators:
  1234:
    first_name: Mario Nicolò
    second_name: De Matteis
    email_address: test@test.it
    birthday: 1900-01-01
    fiscal_code: test
    password: test
    policies:
      - ADMINISTRATOR_IFM_FULL_ACCESS
    active: True

DefaultInvestors:
  - first_name: Mario Nicolò
    second_name: De Matteis
    email_address: test@test.it
    birthday: 1900-01-01
    fiscal_code: test
    password: test
    policies:
      - INVESTOR_DASHBOARD_VISUALISATION
      - INVESTOR_SAMPLING_SCENARIOS
      - INVESTOR_BACKTEST_ALL
    active: True

DefaultFunds:
  DEMO:
    administrators:
      - 1234
    commission_type: percentual
    commission_value: 0
    risk_limits: False
    raising_funds: True

DefaultStrategies:
  - id: TERMINAL
    administrator_id: 1234
    fund_names:
      - DEMO
    category: GENERAL_PURPOSE
  - id: API
    fund_names:
      - DEMO
    category: GENERAL_PURPOSE

Backtesting:
  Tickers:
    - ^GSPC
    - ^IXIC

TradingTickers:
  - US_500
  - BTCUSD

TradingRiskManagement:
  Volume: 0.01
  TakeProfit: 500
  StopLoss: 500
