site_name: Inkosi
repo_url: https://github.com/BopaxDev/Inkosi
repo_name: BopaxDev/Inkosi
theme:
  favicon:
  logo:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate

extra:
  # hide `Made with Material for MkDocs` footer
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BopaxDev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mario-nicolo-de-matteis
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/MDMatteis
    - icon: fontawesome/solid/paper-plane
      link: mailto:marionicdematteis@gmail.com

plugins:
  - search
  - mkdocstrings:
      handlers:
        options:
          paths: [ src ]
          docstring_style: numpy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

  # enable collapsible details blocks
  - admonition
  - pymdownx.details

  # highlight code
  - pymdownx.highlight
  - pymdownx.inlinehilite

  # embed code
  - pymdownx.snippets

copyright: Copyright &copy; 2023 - Mario Nicolò De Matteis